=== PreethiVuchuru27916/fele-simulator/tmpworkspaceforuser/test-data/testSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "required": ["_id", "fmt", "fmId", "channels", "policies", "mod_policy"],
  "$defs": {
    "UUId": {
      "type": "string",
      "pattern": "^[0-9a-fA-F]{8}-?[0-9a-fA-F]{4}-?[0-9a-fA-F]{4}-?[0-9a-fA-F]{4}-?[0-9a-fA-F]{12}$",
      "minLength": 32,
      "maxLength": 36,
      "$comment": "UUID for the unique identification"
    },
    "timestamp": {
      "type" : "string",
      "pattern" : "[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])[T](2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9][Z]",
      "$comment": "Timestamp format to be used globally"
    },
    "policy_type": {
      "type": "string",
      "enum": [ "ImplicitMeta", "Signature" ],
      "$comment": "Possible values for Policy type"
    },
    "policy_name": {
      "type": "string",
      "enum": ["Readers", "Writers", "Admins"],
      "$comment": "Possible values for Policy name"
    }
  },
  "properties": {
    "_id": {
      "type": "string",
      "allOf": [
        { 
          "type": "string",
          "pattern": "^channel[~]",
          "$comment": "Regular expression to ensure _id starts with channel~"
        },
        {
          "type": "string",
          "pattern": "[0-9a-fA-F]{8}-?[0-9a-fA-F]{4}-?[0-9a-fA-F]{4}-?[0-9a-fA-F]{4}-?[0-9a-fA-F]{12}$",
          "$comment": "Regular expression to ensure _id ends with uuid"
        }
       ],
      "minLength": 40,
      "maxLength": 44
    },
    "fmId": {
      "type": "string",
      "$ref": "#/$defs/UUId"
    },
    "fmt": {
      "type": "string",
      "pattern": "^channel$",
      "$comment": "Regular expression that matches exact word `channel`"
    },
    "created_at": {
      "type": "string",
      "$ref": "#/$defs/timestamp"
    },
    "updated_at": {
      "type": "string",
      "$ref": "#/$defs/timestamp"
    },
    "channels": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "required": [ "network_name", "channel_name", "organizations" ],
          "properties": {
              "channel_name": {
                 "type": "string"
              },
          "organizations": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "required": [ "mspid", "rootcertwallet_id" ],
                  "properties": {
                    "mspid": {
                      "type": "string"
                    },
                    "rootcertwallet_id": {
                      "type": "string"
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "mod_policy": {
      "type": "string"
    },
    "policies": {
      "type": "array",
      "items": [{
          "type": "object",
          "required": ["name", "type", "rule"],
          "properties": { 
              "name": { "type": "string", "$ref": "#/$defs/policy_name" },
              "Type": { "type": "string", "$ref": "#/$defs/policy_type" },
              "rule": { "type": "string", "pattern": "[A-Za-z]*" }
          }
      }]
    }
  }
}

=== PreethiVuchuru27916/fele-simulator/tmpworkspaceforuser/test-data/testSchemaData.json
{
  "_id": "channel~9cba7ee4-147c-4108-a85d-cc4de2f7eee0",
  "fmt": "channel",
  "fmId": "9cba7ee4-147c-4108-a85d-cc4de2f7eee0",
  "created_at": "2023-01-01T17:10:47Z",
  "updated_at": "2023-01-05T17:10:47Z",
  "channels": [
    { 
      "network_name": "artemis",
      "channel_name": "myChannel",
      "created_at": "2023-01-01T17:10:47Z",
      "updated_at": "2023-01-06T17:10:47Z",
      "organizations": [
        {
          "mspid": "uhclMSP",
          "rootcertwallet_id": "walletID234"
        },
        {
          "mspid": "utdMSP",
          "rootcertwallet_id": "walletID567"
        }
      ],
      "policies": [
        {
          "name": "Readers",
          "type": "ImplicitMeta",
          "rule": "ANY Readers"
        },
        {
          "name": "Writers",
          "type": "ImplicitMeta",
          "rule": "ANY Writers"
        },
        {
          "name": "Admins",
          "type": "ImplicitMeta",
          "rule": "MAJORITY Admins"
        }
      ]
    }
  ],
  "mod_policy": "Admins",
  "policies": [
    {
      "name": "Readers",
      "type": "ImplicitMeta",
      "rule": "ANY Readers"
    },
    {
      "name": "Writers",
      "type": "ImplicitMeta",
      "rule": "ANY Writers"
    },
    {
      "name": "Admins",
      "type": "ImplicitMeta",
      "rule": "MAJORITY Admins"
    }
  ]
}
